# Generated by Django 4.2.5 on 2023-09-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_reservation_email_reservation_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='firstName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lastName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
