# Generated by Django 4.2.5 on 2023-09-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_reservation_firstname_reservation_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('amenities', models.TextField(null=True)),
                ('pricing_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(null=True, upload_to='styles/')),
            ],
        ),
    ]
