# Generated by Django 4.2.5 on 2023-09-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pricing_per_hour',
            new_name='rate_per_hour',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='pricing_per_hour',
            new_name='rate_per_hour',
        ),
    ]
