# Generated by Django 3.2.6 on 2023-10-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_auto_20231020_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='event_space',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.style'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
